/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authenticatedRouteRouteImport } from './routes/(authenticated)/route'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as authenticatedIndexRouteImport } from './routes/(authenticated)/index'
import { Route as authenticatedGroupsIndexRouteImport } from './routes/(authenticated)/groups/index'
import { Route as authenticatedUsersAtmeIndexRouteImport } from './routes/(authenticated)/users/@me/index'

const authenticatedRouteRoute = authenticatedRouteRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedIndexRoute = authenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authenticatedGroupsIndexRoute =
  authenticatedGroupsIndexRouteImport.update({
    id: '/groups/',
    path: '/groups/',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedUsersAtmeIndexRoute =
  authenticatedUsersAtmeIndexRouteImport.update({
    id: '/users/@me/',
    path: '/users/@me/',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof authenticatedIndexRoute
  '/login/': typeof LoginIndexRoute
  '/groups/': typeof authenticatedGroupsIndexRoute
  '/users/@me/': typeof authenticatedUsersAtmeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof authenticatedIndexRoute
  '/login': typeof LoginIndexRoute
  '/groups': typeof authenticatedGroupsIndexRoute
  '/users/@me': typeof authenticatedUsersAtmeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(authenticated)': typeof authenticatedRouteRouteWithChildren
  '/(authenticated)/': typeof authenticatedIndexRoute
  '/login/': typeof LoginIndexRoute
  '/(authenticated)/groups/': typeof authenticatedGroupsIndexRoute
  '/(authenticated)/users/@me/': typeof authenticatedUsersAtmeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login/' | '/groups/' | '/users/@me/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/groups' | '/users/@me'
  id:
    | '__root__'
    | '/(authenticated)'
    | '/(authenticated)/'
    | '/login/'
    | '/(authenticated)/groups/'
    | '/(authenticated)/users/@me/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authenticatedRouteRoute: typeof authenticatedRouteRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(authenticated)': {
      id: '/(authenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/': {
      id: '/(authenticated)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authenticatedIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/groups/': {
      id: '/(authenticated)/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof authenticatedGroupsIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/users/@me/': {
      id: '/(authenticated)/users/@me/'
      path: '/users/@me'
      fullPath: '/users/@me/'
      preLoaderRoute: typeof authenticatedUsersAtmeIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
  }
}

interface authenticatedRouteRouteChildren {
  authenticatedIndexRoute: typeof authenticatedIndexRoute
  authenticatedGroupsIndexRoute: typeof authenticatedGroupsIndexRoute
  authenticatedUsersAtmeIndexRoute: typeof authenticatedUsersAtmeIndexRoute
}

const authenticatedRouteRouteChildren: authenticatedRouteRouteChildren = {
  authenticatedIndexRoute: authenticatedIndexRoute,
  authenticatedGroupsIndexRoute: authenticatedGroupsIndexRoute,
  authenticatedUsersAtmeIndexRoute: authenticatedUsersAtmeIndexRoute,
}

const authenticatedRouteRouteWithChildren =
  authenticatedRouteRoute._addFileChildren(authenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  authenticatedRouteRoute: authenticatedRouteRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
