/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authenticatedRouteRouteImport } from './routes/(authenticated)/route'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as authenticatedIndexRouteImport } from './routes/(authenticated)/index'
import { Route as AAssetTagIndexRouteImport } from './routes/a/$assetTag/index'
import { Route as authenticatedUsersIndexRouteImport } from './routes/(authenticated)/users/index'
import { Route as authenticatedManufacturersIndexRouteImport } from './routes/(authenticated)/manufacturers/index'
import { Route as authenticatedLocationsIndexRouteImport } from './routes/(authenticated)/locations/index'
import { Route as authenticatedGroupsIndexRouteImport } from './routes/(authenticated)/groups/index'
import { Route as authenticatedAssetsIndexRouteImport } from './routes/(authenticated)/assets/index'
import { Route as authenticatedAssetTypesIndexRouteImport } from './routes/(authenticated)/asset-types/index'
import { Route as authenticatedUsersAtmeIndexRouteImport } from './routes/(authenticated)/users/@me/index'
import { Route as authenticatedUsersUserIDIndexRouteImport } from './routes/(authenticated)/users/$userID/index'

const authenticatedRouteRoute = authenticatedRouteRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedIndexRoute = authenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const AAssetTagIndexRoute = AAssetTagIndexRouteImport.update({
  id: '/a/$assetTag/',
  path: '/a/$assetTag/',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedUsersIndexRoute = authenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authenticatedManufacturersIndexRoute =
  authenticatedManufacturersIndexRouteImport.update({
    id: '/manufacturers/',
    path: '/manufacturers/',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedLocationsIndexRoute =
  authenticatedLocationsIndexRouteImport.update({
    id: '/locations/',
    path: '/locations/',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedGroupsIndexRoute =
  authenticatedGroupsIndexRouteImport.update({
    id: '/groups/',
    path: '/groups/',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedAssetsIndexRoute =
  authenticatedAssetsIndexRouteImport.update({
    id: '/assets/',
    path: '/assets/',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedAssetTypesIndexRoute =
  authenticatedAssetTypesIndexRouteImport.update({
    id: '/asset-types/',
    path: '/asset-types/',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedUsersAtmeIndexRoute =
  authenticatedUsersAtmeIndexRouteImport.update({
    id: '/users/@me/',
    path: '/users/@me/',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedUsersUserIDIndexRoute =
  authenticatedUsersUserIDIndexRouteImport.update({
    id: '/users/$userID/',
    path: '/users/$userID/',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof authenticatedIndexRoute
  '/login/': typeof LoginIndexRoute
  '/asset-types/': typeof authenticatedAssetTypesIndexRoute
  '/assets/': typeof authenticatedAssetsIndexRoute
  '/groups/': typeof authenticatedGroupsIndexRoute
  '/locations/': typeof authenticatedLocationsIndexRoute
  '/manufacturers/': typeof authenticatedManufacturersIndexRoute
  '/users/': typeof authenticatedUsersIndexRoute
  '/a/$assetTag/': typeof AAssetTagIndexRoute
  '/users/$userID/': typeof authenticatedUsersUserIDIndexRoute
  '/users/@me/': typeof authenticatedUsersAtmeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof authenticatedIndexRoute
  '/login': typeof LoginIndexRoute
  '/asset-types': typeof authenticatedAssetTypesIndexRoute
  '/assets': typeof authenticatedAssetsIndexRoute
  '/groups': typeof authenticatedGroupsIndexRoute
  '/locations': typeof authenticatedLocationsIndexRoute
  '/manufacturers': typeof authenticatedManufacturersIndexRoute
  '/users': typeof authenticatedUsersIndexRoute
  '/a/$assetTag': typeof AAssetTagIndexRoute
  '/users/$userID': typeof authenticatedUsersUserIDIndexRoute
  '/users/@me': typeof authenticatedUsersAtmeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(authenticated)': typeof authenticatedRouteRouteWithChildren
  '/(authenticated)/': typeof authenticatedIndexRoute
  '/login/': typeof LoginIndexRoute
  '/(authenticated)/asset-types/': typeof authenticatedAssetTypesIndexRoute
  '/(authenticated)/assets/': typeof authenticatedAssetsIndexRoute
  '/(authenticated)/groups/': typeof authenticatedGroupsIndexRoute
  '/(authenticated)/locations/': typeof authenticatedLocationsIndexRoute
  '/(authenticated)/manufacturers/': typeof authenticatedManufacturersIndexRoute
  '/(authenticated)/users/': typeof authenticatedUsersIndexRoute
  '/a/$assetTag/': typeof AAssetTagIndexRoute
  '/(authenticated)/users/$userID/': typeof authenticatedUsersUserIDIndexRoute
  '/(authenticated)/users/@me/': typeof authenticatedUsersAtmeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login/'
    | '/asset-types/'
    | '/assets/'
    | '/groups/'
    | '/locations/'
    | '/manufacturers/'
    | '/users/'
    | '/a/$assetTag/'
    | '/users/$userID/'
    | '/users/@me/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/asset-types'
    | '/assets'
    | '/groups'
    | '/locations'
    | '/manufacturers'
    | '/users'
    | '/a/$assetTag'
    | '/users/$userID'
    | '/users/@me'
  id:
    | '__root__'
    | '/(authenticated)'
    | '/(authenticated)/'
    | '/login/'
    | '/(authenticated)/asset-types/'
    | '/(authenticated)/assets/'
    | '/(authenticated)/groups/'
    | '/(authenticated)/locations/'
    | '/(authenticated)/manufacturers/'
    | '/(authenticated)/users/'
    | '/a/$assetTag/'
    | '/(authenticated)/users/$userID/'
    | '/(authenticated)/users/@me/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authenticatedRouteRoute: typeof authenticatedRouteRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
  AAssetTagIndexRoute: typeof AAssetTagIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(authenticated)': {
      id: '/(authenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/': {
      id: '/(authenticated)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authenticatedIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/a/$assetTag/': {
      id: '/a/$assetTag/'
      path: '/a/$assetTag'
      fullPath: '/a/$assetTag/'
      preLoaderRoute: typeof AAssetTagIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/users/': {
      id: '/(authenticated)/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof authenticatedUsersIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/manufacturers/': {
      id: '/(authenticated)/manufacturers/'
      path: '/manufacturers'
      fullPath: '/manufacturers/'
      preLoaderRoute: typeof authenticatedManufacturersIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/locations/': {
      id: '/(authenticated)/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof authenticatedLocationsIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/groups/': {
      id: '/(authenticated)/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof authenticatedGroupsIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/assets/': {
      id: '/(authenticated)/assets/'
      path: '/assets'
      fullPath: '/assets/'
      preLoaderRoute: typeof authenticatedAssetsIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/asset-types/': {
      id: '/(authenticated)/asset-types/'
      path: '/asset-types'
      fullPath: '/asset-types/'
      preLoaderRoute: typeof authenticatedAssetTypesIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/users/@me/': {
      id: '/(authenticated)/users/@me/'
      path: '/users/@me'
      fullPath: '/users/@me/'
      preLoaderRoute: typeof authenticatedUsersAtmeIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/users/$userID/': {
      id: '/(authenticated)/users/$userID/'
      path: '/users/$userID'
      fullPath: '/users/$userID/'
      preLoaderRoute: typeof authenticatedUsersUserIDIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
  }
}

interface authenticatedRouteRouteChildren {
  authenticatedIndexRoute: typeof authenticatedIndexRoute
  authenticatedAssetTypesIndexRoute: typeof authenticatedAssetTypesIndexRoute
  authenticatedAssetsIndexRoute: typeof authenticatedAssetsIndexRoute
  authenticatedGroupsIndexRoute: typeof authenticatedGroupsIndexRoute
  authenticatedLocationsIndexRoute: typeof authenticatedLocationsIndexRoute
  authenticatedManufacturersIndexRoute: typeof authenticatedManufacturersIndexRoute
  authenticatedUsersIndexRoute: typeof authenticatedUsersIndexRoute
  authenticatedUsersUserIDIndexRoute: typeof authenticatedUsersUserIDIndexRoute
  authenticatedUsersAtmeIndexRoute: typeof authenticatedUsersAtmeIndexRoute
}

const authenticatedRouteRouteChildren: authenticatedRouteRouteChildren = {
  authenticatedIndexRoute: authenticatedIndexRoute,
  authenticatedAssetTypesIndexRoute: authenticatedAssetTypesIndexRoute,
  authenticatedAssetsIndexRoute: authenticatedAssetsIndexRoute,
  authenticatedGroupsIndexRoute: authenticatedGroupsIndexRoute,
  authenticatedLocationsIndexRoute: authenticatedLocationsIndexRoute,
  authenticatedManufacturersIndexRoute: authenticatedManufacturersIndexRoute,
  authenticatedUsersIndexRoute: authenticatedUsersIndexRoute,
  authenticatedUsersUserIDIndexRoute: authenticatedUsersUserIDIndexRoute,
  authenticatedUsersAtmeIndexRoute: authenticatedUsersAtmeIndexRoute,
}

const authenticatedRouteRouteWithChildren =
  authenticatedRouteRoute._addFileChildren(authenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  authenticatedRouteRoute: authenticatedRouteRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
  AAssetTagIndexRoute: AAssetTagIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
