// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { addPermissionToGroup, addUserToGroup, createAssetType, createGroup, createManufacturer, deleteAssetTypeById, deleteManufacturerById, getAssetTypeById, getCurrentUser, getCurrentUserPermissions, getGroupById, getManufacturerById, health, listAssetTypes, listAuthProviders, listGroupMembers, listGroupPermissions, listGroups, listManufacturers, listUsers, type Options, patchAssetTypeById, patchManufacturerById, removePermissionFromGroup, removeUserFromGroup, updateAssetTypeById, updateManufacturerById } from '../sdk.gen';
import type { AddPermissionToGroupData, AddUserToGroupData, CreateAssetTypeData, CreateAssetTypeError, CreateAssetTypeResponse, CreateGroupData, CreateGroupResponse, CreateManufacturerData, CreateManufacturerError, CreateManufacturerResponse, DeleteAssetTypeByIdData, DeleteAssetTypeByIdError, DeleteAssetTypeByIdResponse, DeleteManufacturerByIdData, DeleteManufacturerByIdError, DeleteManufacturerByIdResponse, GetAssetTypeByIdData, GetAssetTypeByIdError, GetAssetTypeByIdResponse, GetCurrentUserData, GetCurrentUserPermissionsData, GetCurrentUserPermissionsResponse, GetCurrentUserResponse, GetGroupByIdData, GetGroupByIdResponse, GetManufacturerByIdData, GetManufacturerByIdError, GetManufacturerByIdResponse, HealthData, HealthResponse, ListAssetTypesData, ListAssetTypesError, ListAssetTypesResponse, ListAuthProvidersData, ListAuthProvidersResponse, ListGroupMembersData, ListGroupMembersResponse, ListGroupPermissionsData, ListGroupPermissionsResponse, ListGroupsData, ListGroupsResponse, ListManufacturersData, ListManufacturersError, ListManufacturersResponse, ListUsersData, ListUsersResponse, PatchAssetTypeByIdData, PatchAssetTypeByIdError, PatchAssetTypeByIdResponse, PatchManufacturerByIdData, PatchManufacturerByIdError, PatchManufacturerByIdResponse, RemovePermissionFromGroupData, RemoveUserFromGroupData, UpdateAssetTypeByIdData, UpdateAssetTypeByIdError, UpdateAssetTypeByIdResponse, UpdateManufacturerByIdData, UpdateManufacturerByIdError, UpdateManufacturerByIdResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const listAssetTypesQueryKey = (options?: Options<ListAssetTypesData>) => createQueryKey('listAssetTypes', options);

/**
 * List all asset types.
 */
export const listAssetTypesOptions = (options?: Options<ListAssetTypesData>) => queryOptions<ListAssetTypesResponse, ListAssetTypesError, ListAssetTypesResponse, ReturnType<typeof listAssetTypesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listAssetTypes({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listAssetTypesQueryKey(options)
});

/**
 * Create an asset type.
 */
export const createAssetTypeMutation = (options?: Partial<Options<CreateAssetTypeData>>): UseMutationOptions<CreateAssetTypeResponse, CreateAssetTypeError, Options<CreateAssetTypeData>> => {
    const mutationOptions: UseMutationOptions<CreateAssetTypeResponse, CreateAssetTypeError, Options<CreateAssetTypeData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createAssetType({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete an asset type by its ID.
 */
export const deleteAssetTypeByIdMutation = (options?: Partial<Options<DeleteAssetTypeByIdData>>): UseMutationOptions<DeleteAssetTypeByIdResponse, DeleteAssetTypeByIdError, Options<DeleteAssetTypeByIdData>> => {
    const mutationOptions: UseMutationOptions<DeleteAssetTypeByIdResponse, DeleteAssetTypeByIdError, Options<DeleteAssetTypeByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteAssetTypeById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getAssetTypeByIdQueryKey = (options: Options<GetAssetTypeByIdData>) => createQueryKey('getAssetTypeById', options);

/**
 * Get an asset type by its ID.
 */
export const getAssetTypeByIdOptions = (options: Options<GetAssetTypeByIdData>) => queryOptions<GetAssetTypeByIdResponse, GetAssetTypeByIdError, GetAssetTypeByIdResponse, ReturnType<typeof getAssetTypeByIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAssetTypeById({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAssetTypeByIdQueryKey(options)
});

/**
 * Patch individual fields of an asset type by its ID.
 */
export const patchAssetTypeByIdMutation = (options?: Partial<Options<PatchAssetTypeByIdData>>): UseMutationOptions<PatchAssetTypeByIdResponse, PatchAssetTypeByIdError, Options<PatchAssetTypeByIdData>> => {
    const mutationOptions: UseMutationOptions<PatchAssetTypeByIdResponse, PatchAssetTypeByIdError, Options<PatchAssetTypeByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await patchAssetTypeById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Update all fields of an asset type by its ID.
 */
export const updateAssetTypeByIdMutation = (options?: Partial<Options<UpdateAssetTypeByIdData>>): UseMutationOptions<UpdateAssetTypeByIdResponse, UpdateAssetTypeByIdError, Options<UpdateAssetTypeByIdData>> => {
    const mutationOptions: UseMutationOptions<UpdateAssetTypeByIdResponse, UpdateAssetTypeByIdError, Options<UpdateAssetTypeByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateAssetTypeById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listAuthProvidersQueryKey = (options?: Options<ListAuthProvidersData>) => createQueryKey('listAuthProviders', options);

/**
 * List authentication providers.
 */
export const listAuthProvidersOptions = (options?: Options<ListAuthProvidersData>) => queryOptions<ListAuthProvidersResponse, DefaultError, ListAuthProvidersResponse, ReturnType<typeof listAuthProvidersQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listAuthProviders({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listAuthProvidersQueryKey(options)
});

export const listGroupsQueryKey = (options?: Options<ListGroupsData>) => createQueryKey('listGroups', options);

/**
 * List groups.
 */
export const listGroupsOptions = (options?: Options<ListGroupsData>) => queryOptions<ListGroupsResponse, DefaultError, ListGroupsResponse, ReturnType<typeof listGroupsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listGroups({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listGroupsQueryKey(options)
});

/**
 * Create group.
 */
export const createGroupMutation = (options?: Partial<Options<CreateGroupData>>): UseMutationOptions<CreateGroupResponse, DefaultError, Options<CreateGroupData>> => {
    const mutationOptions: UseMutationOptions<CreateGroupResponse, DefaultError, Options<CreateGroupData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createGroup({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getGroupByIdQueryKey = (options: Options<GetGroupByIdData>) => createQueryKey('getGroupById', options);

/**
 * Get group.
 */
export const getGroupByIdOptions = (options: Options<GetGroupByIdData>) => queryOptions<GetGroupByIdResponse, DefaultError, GetGroupByIdResponse, ReturnType<typeof getGroupByIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getGroupById({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getGroupByIdQueryKey(options)
});

/**
 * Remove user from group.
 */
export const removeUserFromGroupMutation = (options?: Partial<Options<RemoveUserFromGroupData>>): UseMutationOptions<unknown, DefaultError, Options<RemoveUserFromGroupData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<RemoveUserFromGroupData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await removeUserFromGroup({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listGroupMembersQueryKey = (options: Options<ListGroupMembersData>) => createQueryKey('listGroupMembers', options);

/**
 * List group members.
 */
export const listGroupMembersOptions = (options: Options<ListGroupMembersData>) => queryOptions<ListGroupMembersResponse, DefaultError, ListGroupMembersResponse, ReturnType<typeof listGroupMembersQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listGroupMembers({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listGroupMembersQueryKey(options)
});

/**
 * Add user to group.
 */
export const addUserToGroupMutation = (options?: Partial<Options<AddUserToGroupData>>): UseMutationOptions<unknown, DefaultError, Options<AddUserToGroupData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<AddUserToGroupData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await addUserToGroup({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Revoke permission from group.
 */
export const removePermissionFromGroupMutation = (options?: Partial<Options<RemovePermissionFromGroupData>>): UseMutationOptions<unknown, DefaultError, Options<RemovePermissionFromGroupData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<RemovePermissionFromGroupData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await removePermissionFromGroup({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listGroupPermissionsQueryKey = (options: Options<ListGroupPermissionsData>) => createQueryKey('listGroupPermissions', options);

/**
 * List group permissions.
 */
export const listGroupPermissionsOptions = (options: Options<ListGroupPermissionsData>) => queryOptions<ListGroupPermissionsResponse, DefaultError, ListGroupPermissionsResponse, ReturnType<typeof listGroupPermissionsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listGroupPermissions({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listGroupPermissionsQueryKey(options)
});

/**
 * Grant permission to group.
 */
export const addPermissionToGroupMutation = (options?: Partial<Options<AddPermissionToGroupData>>): UseMutationOptions<unknown, DefaultError, Options<AddPermissionToGroupData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<AddPermissionToGroupData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await addPermissionToGroup({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const healthQueryKey = (options?: Options<HealthData>) => createQueryKey('health', options);

/**
 * Get health of the API.
 */
export const healthOptions = (options?: Options<HealthData>) => queryOptions<HealthResponse, DefaultError, HealthResponse, ReturnType<typeof healthQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await health({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: healthQueryKey(options)
});

export const listManufacturersQueryKey = (options?: Options<ListManufacturersData>) => createQueryKey('listManufacturers', options);

/**
 * List all manufacturers.
 */
export const listManufacturersOptions = (options?: Options<ListManufacturersData>) => queryOptions<ListManufacturersResponse, ListManufacturersError, ListManufacturersResponse, ReturnType<typeof listManufacturersQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listManufacturers({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listManufacturersQueryKey(options)
});

/**
 * Create a manufacturer.
 */
export const createManufacturerMutation = (options?: Partial<Options<CreateManufacturerData>>): UseMutationOptions<CreateManufacturerResponse, CreateManufacturerError, Options<CreateManufacturerData>> => {
    const mutationOptions: UseMutationOptions<CreateManufacturerResponse, CreateManufacturerError, Options<CreateManufacturerData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createManufacturer({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete a manufacturer by its ID.
 */
export const deleteManufacturerByIdMutation = (options?: Partial<Options<DeleteManufacturerByIdData>>): UseMutationOptions<DeleteManufacturerByIdResponse, DeleteManufacturerByIdError, Options<DeleteManufacturerByIdData>> => {
    const mutationOptions: UseMutationOptions<DeleteManufacturerByIdResponse, DeleteManufacturerByIdError, Options<DeleteManufacturerByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteManufacturerById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getManufacturerByIdQueryKey = (options: Options<GetManufacturerByIdData>) => createQueryKey('getManufacturerById', options);

/**
 * Get a manufacturer by its ID.
 */
export const getManufacturerByIdOptions = (options: Options<GetManufacturerByIdData>) => queryOptions<GetManufacturerByIdResponse, GetManufacturerByIdError, GetManufacturerByIdResponse, ReturnType<typeof getManufacturerByIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getManufacturerById({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getManufacturerByIdQueryKey(options)
});

/**
 * Patch individual fields of a manufacturer by its ID.
 */
export const patchManufacturerByIdMutation = (options?: Partial<Options<PatchManufacturerByIdData>>): UseMutationOptions<PatchManufacturerByIdResponse, PatchManufacturerByIdError, Options<PatchManufacturerByIdData>> => {
    const mutationOptions: UseMutationOptions<PatchManufacturerByIdResponse, PatchManufacturerByIdError, Options<PatchManufacturerByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await patchManufacturerById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Update all fields of a manufacturer by its ID.
 */
export const updateManufacturerByIdMutation = (options?: Partial<Options<UpdateManufacturerByIdData>>): UseMutationOptions<UpdateManufacturerByIdResponse, UpdateManufacturerByIdError, Options<UpdateManufacturerByIdData>> => {
    const mutationOptions: UseMutationOptions<UpdateManufacturerByIdResponse, UpdateManufacturerByIdError, Options<UpdateManufacturerByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateManufacturerById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listUsersQueryKey = (options?: Options<ListUsersData>) => createQueryKey('listUsers', options);

/**
 * List all users.
 */
export const listUsersOptions = (options?: Options<ListUsersData>) => queryOptions<ListUsersResponse, DefaultError, ListUsersResponse, ReturnType<typeof listUsersQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listUsers({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listUsersQueryKey(options)
});

export const getCurrentUserQueryKey = (options?: Options<GetCurrentUserData>) => createQueryKey('getCurrentUser', options);

/**
 * Get current user.
 */
export const getCurrentUserOptions = (options?: Options<GetCurrentUserData>) => queryOptions<GetCurrentUserResponse, DefaultError, GetCurrentUserResponse, ReturnType<typeof getCurrentUserQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getCurrentUser({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getCurrentUserQueryKey(options)
});

export const getCurrentUserPermissionsQueryKey = (options?: Options<GetCurrentUserPermissionsData>) => createQueryKey('getCurrentUserPermissions', options);

/**
 * Get the current user's permissions.
 */
export const getCurrentUserPermissionsOptions = (options?: Options<GetCurrentUserPermissionsData>) => queryOptions<GetCurrentUserPermissionsResponse, DefaultError, GetCurrentUserPermissionsResponse, ReturnType<typeof getCurrentUserPermissionsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getCurrentUserPermissions({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getCurrentUserPermissionsQueryKey(options)
});
