// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { AddPermissionToGroupData, AddPermissionToGroupErrors, AddPermissionToGroupResponses, AddUserToGroupData, AddUserToGroupErrors, AddUserToGroupResponses, CreateAssetTypeData, CreateAssetTypeErrors, CreateAssetTypeResponses, CreateGroupData, CreateGroupResponses, CreateManufacturerData, CreateManufacturerErrors, CreateManufacturerResponses, DeleteAssetTypeByIdData, DeleteAssetTypeByIdErrors, DeleteAssetTypeByIdResponses, DeleteManufacturerByIdData, DeleteManufacturerByIdErrors, DeleteManufacturerByIdResponses, GetAssetTypeByIdData, GetAssetTypeByIdErrors, GetAssetTypeByIdResponses, GetCurrentUserData, GetCurrentUserPermissionsData, GetCurrentUserPermissionsResponses, GetCurrentUserResponses, GetGroupByIdData, GetGroupByIdErrors, GetGroupByIdResponses, GetManufacturerByIdData, GetManufacturerByIdErrors, GetManufacturerByIdResponses, Health2Data, Health2Responses, HealthData, HealthResponses, ListAssetTypesData, ListAssetTypesErrors, ListAssetTypesResponses, ListAuthProvidersData, ListAuthProvidersResponses, ListGroupMembersData, ListGroupMembersErrors, ListGroupMembersResponses, ListGroupPermissionsData, ListGroupPermissionsErrors, ListGroupPermissionsResponses, ListGroupsData, ListGroupsResponses, ListManufacturersData, ListManufacturersErrors, ListManufacturersResponses, ListUsersData, ListUsersResponses, PatchAssetTypeByIdData, PatchAssetTypeByIdErrors, PatchAssetTypeByIdResponses, PatchManufacturerByIdData, PatchManufacturerByIdErrors, PatchManufacturerByIdResponses, RemovePermissionFromGroupData, RemovePermissionFromGroupErrors, RemovePermissionFromGroupResponses, RemoveUserFromGroupData, RemoveUserFromGroupErrors, RemoveUserFromGroupResponses, UpdateAssetTypeByIdData, UpdateAssetTypeByIdErrors, UpdateAssetTypeByIdResponses, UpdateManufacturerByIdData, UpdateManufacturerByIdErrors, UpdateManufacturerByIdResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * List all asset types.
 */
export const listAssetTypes = <ThrowOnError extends boolean = false>(options?: Options<ListAssetTypesData, ThrowOnError>): RequestResult<ListAssetTypesResponses, ListAssetTypesErrors, ThrowOnError> => (options?.client ?? client).get<ListAssetTypesResponses, ListAssetTypesErrors, ThrowOnError>({ url: '/asset/type', ...options });

/**
 * Create an asset type.
 */
export const createAssetType = <ThrowOnError extends boolean = false>(options: Options<CreateAssetTypeData, ThrowOnError>): RequestResult<CreateAssetTypeResponses, CreateAssetTypeErrors, ThrowOnError> => (options.client ?? client).post<CreateAssetTypeResponses, CreateAssetTypeErrors, ThrowOnError>({
    url: '/asset/type',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete an asset type by its ID.
 */
export const deleteAssetTypeById = <ThrowOnError extends boolean = false>(options: Options<DeleteAssetTypeByIdData, ThrowOnError>): RequestResult<DeleteAssetTypeByIdResponses, DeleteAssetTypeByIdErrors, ThrowOnError> => (options.client ?? client).delete<DeleteAssetTypeByIdResponses, DeleteAssetTypeByIdErrors, ThrowOnError>({ url: '/asset/type/{id}', ...options });

/**
 * Get an asset type by its ID.
 */
export const getAssetTypeById = <ThrowOnError extends boolean = false>(options: Options<GetAssetTypeByIdData, ThrowOnError>): RequestResult<GetAssetTypeByIdResponses, GetAssetTypeByIdErrors, ThrowOnError> => (options.client ?? client).get<GetAssetTypeByIdResponses, GetAssetTypeByIdErrors, ThrowOnError>({ url: '/asset/type/{id}', ...options });

/**
 * Patch individual fields of an asset type by its ID.
 */
export const patchAssetTypeById = <ThrowOnError extends boolean = false>(options: Options<PatchAssetTypeByIdData, ThrowOnError>): RequestResult<PatchAssetTypeByIdResponses, PatchAssetTypeByIdErrors, ThrowOnError> => (options.client ?? client).patch<PatchAssetTypeByIdResponses, PatchAssetTypeByIdErrors, ThrowOnError>({
    url: '/asset/type/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Update all fields of an asset type by its ID.
 */
export const updateAssetTypeById = <ThrowOnError extends boolean = false>(options: Options<UpdateAssetTypeByIdData, ThrowOnError>): RequestResult<UpdateAssetTypeByIdResponses, UpdateAssetTypeByIdErrors, ThrowOnError> => (options.client ?? client).put<UpdateAssetTypeByIdResponses, UpdateAssetTypeByIdErrors, ThrowOnError>({
    url: '/asset/type/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List authentication providers.
 */
export const listAuthProviders = <ThrowOnError extends boolean = false>(options?: Options<ListAuthProvidersData, ThrowOnError>): RequestResult<ListAuthProvidersResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListAuthProvidersResponses, unknown, ThrowOnError>({ url: '/auth/providers', ...options });

/**
 * List groups.
 */
export const listGroups = <ThrowOnError extends boolean = false>(options?: Options<ListGroupsData, ThrowOnError>): RequestResult<ListGroupsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListGroupsResponses, unknown, ThrowOnError>({ url: '/group', ...options });

/**
 * Create group.
 */
export const createGroup = <ThrowOnError extends boolean = false>(options: Options<CreateGroupData, ThrowOnError>): RequestResult<CreateGroupResponses, unknown, ThrowOnError> => (options.client ?? client).post<CreateGroupResponses, unknown, ThrowOnError>({
    url: '/group',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get group.
 */
export const getGroupById = <ThrowOnError extends boolean = false>(options: Options<GetGroupByIdData, ThrowOnError>): RequestResult<GetGroupByIdResponses, GetGroupByIdErrors, ThrowOnError> => (options.client ?? client).get<GetGroupByIdResponses, GetGroupByIdErrors, ThrowOnError>({ url: '/group/{group_id}', ...options });

/**
 * Remove user from group.
 */
export const removeUserFromGroup = <ThrowOnError extends boolean = false>(options: Options<RemoveUserFromGroupData, ThrowOnError>): RequestResult<RemoveUserFromGroupResponses, RemoveUserFromGroupErrors, ThrowOnError> => (options.client ?? client).delete<RemoveUserFromGroupResponses, RemoveUserFromGroupErrors, ThrowOnError>({
    url: '/group/{group_id}/members',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List group members.
 */
export const listGroupMembers = <ThrowOnError extends boolean = false>(options: Options<ListGroupMembersData, ThrowOnError>): RequestResult<ListGroupMembersResponses, ListGroupMembersErrors, ThrowOnError> => (options.client ?? client).get<ListGroupMembersResponses, ListGroupMembersErrors, ThrowOnError>({ url: '/group/{group_id}/members', ...options });

/**
 * Add user to group.
 */
export const addUserToGroup = <ThrowOnError extends boolean = false>(options: Options<AddUserToGroupData, ThrowOnError>): RequestResult<AddUserToGroupResponses, AddUserToGroupErrors, ThrowOnError> => (options.client ?? client).post<AddUserToGroupResponses, AddUserToGroupErrors, ThrowOnError>({
    url: '/group/{group_id}/members',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Revoke permission from group.
 */
export const removePermissionFromGroup = <ThrowOnError extends boolean = false>(options: Options<RemovePermissionFromGroupData, ThrowOnError>): RequestResult<RemovePermissionFromGroupResponses, RemovePermissionFromGroupErrors, ThrowOnError> => (options.client ?? client).delete<RemovePermissionFromGroupResponses, RemovePermissionFromGroupErrors, ThrowOnError>({
    url: '/group/{group_id}/permissions',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List group permissions.
 */
export const listGroupPermissions = <ThrowOnError extends boolean = false>(options: Options<ListGroupPermissionsData, ThrowOnError>): RequestResult<ListGroupPermissionsResponses, ListGroupPermissionsErrors, ThrowOnError> => (options.client ?? client).get<ListGroupPermissionsResponses, ListGroupPermissionsErrors, ThrowOnError>({ url: '/group/{group_id}/permissions', ...options });

/**
 * Grant permission to group.
 */
export const addPermissionToGroup = <ThrowOnError extends boolean = false>(options: Options<AddPermissionToGroupData, ThrowOnError>): RequestResult<AddPermissionToGroupResponses, AddPermissionToGroupErrors, ThrowOnError> => (options.client ?? client).post<AddPermissionToGroupResponses, AddPermissionToGroupErrors, ThrowOnError>({
    url: '/group/{group_id}/permissions',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get health of the API.
 */
export const health = <ThrowOnError extends boolean = false>(options?: Options<HealthData, ThrowOnError>): RequestResult<HealthResponses, unknown, ThrowOnError> => (options?.client ?? client).get<HealthResponses, unknown, ThrowOnError>({ url: '/health', ...options });

/**
 * Get health of the API.
 */
export const health2 = <ThrowOnError extends boolean = false>(options?: Options<Health2Data, ThrowOnError>): RequestResult<Health2Responses, unknown, ThrowOnError> => (options?.client ?? client).head<Health2Responses, unknown, ThrowOnError>({ url: '/health', ...options });

/**
 * List all manufacturers.
 */
export const listManufacturers = <ThrowOnError extends boolean = false>(options?: Options<ListManufacturersData, ThrowOnError>): RequestResult<ListManufacturersResponses, ListManufacturersErrors, ThrowOnError> => (options?.client ?? client).get<ListManufacturersResponses, ListManufacturersErrors, ThrowOnError>({ url: '/manufacturer', ...options });

/**
 * Create a manufacturer.
 */
export const createManufacturer = <ThrowOnError extends boolean = false>(options: Options<CreateManufacturerData, ThrowOnError>): RequestResult<CreateManufacturerResponses, CreateManufacturerErrors, ThrowOnError> => (options.client ?? client).post<CreateManufacturerResponses, CreateManufacturerErrors, ThrowOnError>({
    url: '/manufacturer',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete a manufacturer by its ID.
 */
export const deleteManufacturerById = <ThrowOnError extends boolean = false>(options: Options<DeleteManufacturerByIdData, ThrowOnError>): RequestResult<DeleteManufacturerByIdResponses, DeleteManufacturerByIdErrors, ThrowOnError> => (options.client ?? client).delete<DeleteManufacturerByIdResponses, DeleteManufacturerByIdErrors, ThrowOnError>({ url: '/manufacturer/{id}', ...options });

/**
 * Get a manufacturer by its ID.
 */
export const getManufacturerById = <ThrowOnError extends boolean = false>(options: Options<GetManufacturerByIdData, ThrowOnError>): RequestResult<GetManufacturerByIdResponses, GetManufacturerByIdErrors, ThrowOnError> => (options.client ?? client).get<GetManufacturerByIdResponses, GetManufacturerByIdErrors, ThrowOnError>({ url: '/manufacturer/{id}', ...options });

/**
 * Patch individual fields of a manufacturer by its ID.
 */
export const patchManufacturerById = <ThrowOnError extends boolean = false>(options: Options<PatchManufacturerByIdData, ThrowOnError>): RequestResult<PatchManufacturerByIdResponses, PatchManufacturerByIdErrors, ThrowOnError> => (options.client ?? client).patch<PatchManufacturerByIdResponses, PatchManufacturerByIdErrors, ThrowOnError>({
    url: '/manufacturer/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Update all fields of a manufacturer by its ID.
 */
export const updateManufacturerById = <ThrowOnError extends boolean = false>(options: Options<UpdateManufacturerByIdData, ThrowOnError>): RequestResult<UpdateManufacturerByIdResponses, UpdateManufacturerByIdErrors, ThrowOnError> => (options.client ?? client).put<UpdateManufacturerByIdResponses, UpdateManufacturerByIdErrors, ThrowOnError>({
    url: '/manufacturer/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List all users.
 */
export const listUsers = <ThrowOnError extends boolean = false>(options?: Options<ListUsersData, ThrowOnError>): RequestResult<ListUsersResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListUsersResponses, unknown, ThrowOnError>({ url: '/user', ...options });

/**
 * Get current user.
 */
export const getCurrentUser = <ThrowOnError extends boolean = false>(options?: Options<GetCurrentUserData, ThrowOnError>): RequestResult<GetCurrentUserResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetCurrentUserResponses, unknown, ThrowOnError>({ url: '/user/@me', ...options });

/**
 * Get the current user's permissions.
 */
export const getCurrentUserPermissions = <ThrowOnError extends boolean = false>(options?: Options<GetCurrentUserPermissionsData, ThrowOnError>): RequestResult<GetCurrentUserPermissionsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetCurrentUserPermissionsResponses, unknown, ThrowOnError>({ url: '/user/@me/permissions', ...options });
