// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api/v1` | (string & {});
};

export type AssetType = {
    manufacturer: string;
    name: string;
    product_url?: string | null;
    value?: null | SchemaDecimal;
};

export type AssetTypeDto = {
    id: string;
    manufacturer: string;
    name: string;
    product_url?: string | null;
    value?: null | SchemaDecimal;
};

export type CreateGroup = {
    name: string;
};

export type ErrorResponse = {
    error: string;
};

export type GroupInfo = {
    id: string;
    name: string;
};

export type GroupMembers = {
    members: Array<UserInfo>;
};

export type Manufacturer = {
    description?: string | null;
    email?: string | null;
    name: string;
    phone?: string | null;
    website?: string | null;
};

export type ManufacturerInfo = {
    description?: string | null;
    email?: string | null;
    id: string;
    name: string;
    phone?: string | null;
    website?: string | null;
};

export type ModifyMember = {
    member: string;
};

export type ObjectPermissions = {
    actions: Array<string>;
    name: string;
};

export type PatchAssetType = {
    manufacturer?: string | null;
    name?: string | null;
    product_url?: string | null;
    value?: null | SchemaDecimal;
};

export type PatchManufacturer = {
    description?: string | null;
    email?: string | null;
    name?: string | null;
    phone?: string | null;
    website?: string | null;
};

export type PermissionRef = {
    action: string;
    object: string;
};

export type ProviderInfo = {
    id: string;
    name: string;
};

export type SchemaDecimal = number;

export type UserInfo = {
    email: string;
    id: string;
    name: string;
};

export type ListAssetTypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/asset/type';
};

export type ListAssetTypesErrors = {
    /**
     * Missing permission
     */
    401: ErrorResponse;
};

export type ListAssetTypesError = ListAssetTypesErrors[keyof ListAssetTypesErrors];

export type ListAssetTypesResponses = {
    /**
     * Success
     */
    200: Array<AssetTypeDto>;
};

export type ListAssetTypesResponse = ListAssetTypesResponses[keyof ListAssetTypesResponses];

export type CreateAssetTypeData = {
    body: AssetType;
    path?: never;
    query?: never;
    url: '/asset/type';
};

export type CreateAssetTypeErrors = {
    /**
     * Manufacturer by that ID not found
     */
    400: ErrorResponse;
    /**
     * Missing permission
     */
    401: ErrorResponse;
};

export type CreateAssetTypeError = CreateAssetTypeErrors[keyof CreateAssetTypeErrors];

export type CreateAssetTypeResponses = {
    /**
     * Success
     */
    200: AssetTypeDto;
};

export type CreateAssetTypeResponse = CreateAssetTypeResponses[keyof CreateAssetTypeResponses];

export type DeleteAssetTypeByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/asset/type/{id}';
};

export type DeleteAssetTypeByIdErrors = {
    /**
     * Missing permission
     */
    401: ErrorResponse;
    /**
     * Asset type by that ID not found
     */
    404: ErrorResponse;
};

export type DeleteAssetTypeByIdError = DeleteAssetTypeByIdErrors[keyof DeleteAssetTypeByIdErrors];

export type DeleteAssetTypeByIdResponses = {
    /**
     * Success
     */
    204: void;
};

export type DeleteAssetTypeByIdResponse = DeleteAssetTypeByIdResponses[keyof DeleteAssetTypeByIdResponses];

export type GetAssetTypeByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/asset/type/{id}';
};

export type GetAssetTypeByIdErrors = {
    /**
     * Missing permission
     */
    401: ErrorResponse;
    /**
     * Asset type by that ID not found
     */
    404: ErrorResponse;
};

export type GetAssetTypeByIdError = GetAssetTypeByIdErrors[keyof GetAssetTypeByIdErrors];

export type GetAssetTypeByIdResponses = {
    /**
     * Success
     */
    200: AssetTypeDto;
};

export type GetAssetTypeByIdResponse = GetAssetTypeByIdResponses[keyof GetAssetTypeByIdResponses];

export type PatchAssetTypeByIdData = {
    body: PatchAssetType;
    path: {
        id: string;
    };
    query?: never;
    url: '/asset/type/{id}';
};

export type PatchAssetTypeByIdErrors = {
    /**
     * Missing permission
     */
    401: ErrorResponse;
    /**
     * Manufacturer by that ID not found
     */
    404: ErrorResponse;
};

export type PatchAssetTypeByIdError = PatchAssetTypeByIdErrors[keyof PatchAssetTypeByIdErrors];

export type PatchAssetTypeByIdResponses = {
    /**
     * Success
     */
    200: AssetTypeDto;
};

export type PatchAssetTypeByIdResponse = PatchAssetTypeByIdResponses[keyof PatchAssetTypeByIdResponses];

export type UpdateAssetTypeByIdData = {
    body: AssetType;
    path: {
        id: string;
    };
    query?: never;
    url: '/asset/type/{id}';
};

export type UpdateAssetTypeByIdErrors = {
    /**
     * Missing permission
     */
    401: ErrorResponse;
    /**
     * Asset type by that ID not found
     */
    404: ErrorResponse;
};

export type UpdateAssetTypeByIdError = UpdateAssetTypeByIdErrors[keyof UpdateAssetTypeByIdErrors];

export type UpdateAssetTypeByIdResponses = {
    /**
     * Success
     */
    200: AssetTypeDto;
};

export type UpdateAssetTypeByIdResponse = UpdateAssetTypeByIdResponses[keyof UpdateAssetTypeByIdResponses];

export type ListAuthProvidersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/providers';
};

export type ListAuthProvidersResponses = {
    /**
     * Success
     */
    200: Array<ProviderInfo>;
};

export type ListAuthProvidersResponse = ListAuthProvidersResponses[keyof ListAuthProvidersResponses];

export type ListGroupsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/group';
};

export type ListGroupsResponses = {
    /**
     * Success
     */
    200: Array<GroupInfo>;
};

export type ListGroupsResponse = ListGroupsResponses[keyof ListGroupsResponses];

export type CreateGroupData = {
    body: CreateGroup;
    path?: never;
    query?: never;
    url: '/group';
};

export type CreateGroupResponses = {
    /**
     * Success
     */
    200: GroupInfo;
};

export type CreateGroupResponse = CreateGroupResponses[keyof CreateGroupResponses];

export type GetGroupByIdData = {
    body?: never;
    path: {
        group_id: string;
    };
    query?: never;
    url: '/group/{group_id}';
};

export type GetGroupByIdErrors = {
    /**
     * Not found
     */
    404: unknown;
};

export type GetGroupByIdResponses = {
    /**
     * Success
     */
    200: GroupInfo;
};

export type GetGroupByIdResponse = GetGroupByIdResponses[keyof GetGroupByIdResponses];

export type RemoveUserFromGroupData = {
    body: ModifyMember;
    path: {
        group_id: string;
    };
    query?: never;
    url: '/group/{group_id}/members';
};

export type RemoveUserFromGroupErrors = {
    /**
     * Not found
     */
    404: unknown;
};

export type RemoveUserFromGroupResponses = {
    /**
     * Success
     */
    201: unknown;
};

export type ListGroupMembersData = {
    body?: never;
    path: {
        group_id: string;
    };
    query?: never;
    url: '/group/{group_id}/members';
};

export type ListGroupMembersErrors = {
    /**
     * Not found
     */
    404: unknown;
};

export type ListGroupMembersResponses = {
    /**
     * Success
     */
    200: GroupMembers;
};

export type ListGroupMembersResponse = ListGroupMembersResponses[keyof ListGroupMembersResponses];

export type AddUserToGroupData = {
    body: ModifyMember;
    path: {
        group_id: string;
    };
    query?: never;
    url: '/group/{group_id}/members';
};

export type AddUserToGroupErrors = {
    /**
     * Not found
     */
    404: unknown;
};

export type AddUserToGroupResponses = {
    /**
     * Success
     */
    201: unknown;
};

export type RemovePermissionFromGroupData = {
    body: PermissionRef;
    path: {
        group_id: string;
    };
    query?: never;
    url: '/group/{group_id}/permissions';
};

export type RemovePermissionFromGroupErrors = {
    /**
     * Not found
     */
    404: unknown;
};

export type RemovePermissionFromGroupResponses = {
    /**
     * Success
     */
    201: unknown;
};

export type ListGroupPermissionsData = {
    body?: never;
    path: {
        group_id: string;
    };
    query?: never;
    url: '/group/{group_id}/permissions';
};

export type ListGroupPermissionsErrors = {
    /**
     * Not found
     */
    404: unknown;
};

export type ListGroupPermissionsResponses = {
    /**
     * Success
     */
    200: Array<ObjectPermissions>;
};

export type ListGroupPermissionsResponse = ListGroupPermissionsResponses[keyof ListGroupPermissionsResponses];

export type AddPermissionToGroupData = {
    body: PermissionRef;
    path: {
        group_id: string;
    };
    query?: never;
    url: '/group/{group_id}/permissions';
};

export type AddPermissionToGroupErrors = {
    /**
     * Not found
     */
    404: unknown;
};

export type AddPermissionToGroupResponses = {
    /**
     * Success
     */
    201: unknown;
};

export type HealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthResponses = {
    /**
     * Success
     */
    200: string;
};

export type HealthResponse = HealthResponses[keyof HealthResponses];

export type Health2Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type Health2Responses = {
    /**
     * Success
     */
    200: string;
};

export type Health2Response = Health2Responses[keyof Health2Responses];

export type ListManufacturersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/manufacturer';
};

export type ListManufacturersErrors = {
    /**
     * Missing permission
     */
    401: ErrorResponse;
};

export type ListManufacturersError = ListManufacturersErrors[keyof ListManufacturersErrors];

export type ListManufacturersResponses = {
    /**
     * Success
     */
    200: Array<ManufacturerInfo>;
};

export type ListManufacturersResponse = ListManufacturersResponses[keyof ListManufacturersResponses];

export type CreateManufacturerData = {
    body: Manufacturer;
    path?: never;
    query?: never;
    url: '/manufacturer';
};

export type CreateManufacturerErrors = {
    /**
     * Missing permission
     */
    401: ErrorResponse;
};

export type CreateManufacturerError = CreateManufacturerErrors[keyof CreateManufacturerErrors];

export type CreateManufacturerResponses = {
    /**
     * Success
     */
    200: ManufacturerInfo;
};

export type CreateManufacturerResponse = CreateManufacturerResponses[keyof CreateManufacturerResponses];

export type DeleteManufacturerByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/manufacturer/{id}';
};

export type DeleteManufacturerByIdErrors = {
    /**
     * Missing permission
     */
    401: ErrorResponse;
    /**
     * Manufacturer by that ID not found
     */
    404: ErrorResponse;
};

export type DeleteManufacturerByIdError = DeleteManufacturerByIdErrors[keyof DeleteManufacturerByIdErrors];

export type DeleteManufacturerByIdResponses = {
    /**
     * Success
     */
    204: void;
};

export type DeleteManufacturerByIdResponse = DeleteManufacturerByIdResponses[keyof DeleteManufacturerByIdResponses];

export type GetManufacturerByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/manufacturer/{id}';
};

export type GetManufacturerByIdErrors = {
    /**
     * Missing permission
     */
    401: ErrorResponse;
    /**
     * Manufacturer by that ID not found
     */
    404: ErrorResponse;
};

export type GetManufacturerByIdError = GetManufacturerByIdErrors[keyof GetManufacturerByIdErrors];

export type GetManufacturerByIdResponses = {
    /**
     * Success
     */
    200: ManufacturerInfo;
};

export type GetManufacturerByIdResponse = GetManufacturerByIdResponses[keyof GetManufacturerByIdResponses];

export type PatchManufacturerByIdData = {
    body: PatchManufacturer;
    path: {
        id: string;
    };
    query?: never;
    url: '/manufacturer/{id}';
};

export type PatchManufacturerByIdErrors = {
    /**
     * Missing permission
     */
    401: ErrorResponse;
    /**
     * Manufacturer by that ID not found
     */
    404: ErrorResponse;
};

export type PatchManufacturerByIdError = PatchManufacturerByIdErrors[keyof PatchManufacturerByIdErrors];

export type PatchManufacturerByIdResponses = {
    /**
     * Success
     */
    200: ManufacturerInfo;
};

export type PatchManufacturerByIdResponse = PatchManufacturerByIdResponses[keyof PatchManufacturerByIdResponses];

export type UpdateManufacturerByIdData = {
    body: Manufacturer;
    path: {
        id: string;
    };
    query?: never;
    url: '/manufacturer/{id}';
};

export type UpdateManufacturerByIdErrors = {
    /**
     * Missing permission
     */
    401: ErrorResponse;
    /**
     * Manufacturer by that ID not found
     */
    404: ErrorResponse;
};

export type UpdateManufacturerByIdError = UpdateManufacturerByIdErrors[keyof UpdateManufacturerByIdErrors];

export type UpdateManufacturerByIdResponses = {
    /**
     * Success
     */
    200: ManufacturerInfo;
};

export type UpdateManufacturerByIdResponse = UpdateManufacturerByIdResponses[keyof UpdateManufacturerByIdResponses];

export type ListUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user';
};

export type ListUsersResponses = {
    /**
     * Success
     */
    200: Array<UserInfo>;
};

export type ListUsersResponse = ListUsersResponses[keyof ListUsersResponses];

export type GetCurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/@me';
};

export type GetCurrentUserResponses = {
    /**
     * Success
     */
    200: UserInfo;
};

export type GetCurrentUserResponse = GetCurrentUserResponses[keyof GetCurrentUserResponses];

export type GetCurrentUserPermissionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/@me/permissions';
};

export type GetCurrentUserPermissionsResponses = {
    /**
     * Success
     */
    200: Array<ObjectPermissions>;
};

export type GetCurrentUserPermissionsResponse = GetCurrentUserPermissionsResponses[keyof GetCurrentUserPermissionsResponses];
