// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api/v1` | (string & {});
};

export type AssetBundleDto = {
    id: string;
};

export type AssetDto = {
    /**
     * An optional alias for this asset. This is purely for convenience
     * in searching for and identifying multiple instances of similar
     * assets.
     */
    alias?: string | null;
    /**
     * An optional bundle that this asset is within, as asset bundle
     * identifier.
     */
    bundle?: string | null;
    /**
     * The unique identifier for this asset. This property is immutable.
     */
    id: string;
    locations: AssetLocations;
    /**
     * An optional field for miscellaneous notes about the asset.
     */
    notes?: string | null;
    /**
     * The asset tag attached to this asset.
     */
    tag: string;
    /**
     * The type of this asset, as an asset type identifier. This property
     * is immutable.
     */
    type: string;
};

export type AssetLocations = {
    /**
     * The current location of an asset. This property is only mutable
     * via its dedicated field endpoints.
     */
    current: string;
    /**
     * The default/home location of this asset. This is used to mark where
     * an asset *should* be when not assigned to a project.
     */
    home: string;
};

export type AssetType = {
    manufacturer: string;
    name: string;
    product_url?: string | null;
    value?: null | SchemaDecimal;
};

export type AssetTypeDto = {
    id: string;
    manufacturer: string;
    name: string;
    product_url?: string | null;
    value?: null | SchemaDecimal;
};

export type ContactDetailsDto = {
    links: Array<ContactDetailsLinkDto>;
    name?: string | null;
};

export type ContactDetailsLinkDto = {
    label?: string | null;
    link: string;
};

export type Coordinates = [
    number,
    number
];

export type CreateAssetRequest = {
    alias?: string | null;
    bundle?: string | null;
    locations: AssetLocations;
    notes?: string | null;
    tag: string;
    type: string;
};

export type CreateGroup = {
    name: string;
};

export type CreateLabelRequest = {
    blocking: boolean;
    colour?: string | null;
    description?: string | null;
    name: string;
};

export type ErrorResponse = {
    error: string;
};

export type GroupInfo = {
    id: string;
    name: string;
};

export type GroupMembers = {
    members: Array<UserDto>;
};

export type LabelDto = {
    blocking: boolean;
    colour?: string | null;
    description?: string | null;
    id: string;
    name: string;
};

export type Location = {
    coordinates?: null | Coordinates;
    description?: string | null;
    name: string;
};

export type LocationDto = {
    coordinates?: null | Coordinates;
    description?: string | null;
    id: string;
    name: string;
};

export type Manufacturer = {
    description?: string | null;
    email?: string | null;
    name: string;
    phone?: string | null;
    website?: string | null;
};

export type ManufacturerInfo = {
    description?: string | null;
    email?: string | null;
    id: string;
    name: string;
    phone?: string | null;
    website?: string | null;
};

export type ModifyMember = {
    member: string;
};

export type ObjectPermissions = {
    actions: Array<string>;
    name: string;
};

export type PatchAssetType = {
    manufacturer?: string | null;
    name?: string | null;
    product_url?: string | null;
    value?: null | SchemaDecimal;
};

export type PatchLocation = {
    coordinates?: null | Coordinates;
    description?: string | null;
    name?: string | null;
};

export type PatchManufacturer = {
    description?: string | null;
    email?: string | null;
    name?: string | null;
    phone?: string | null;
    website?: string | null;
};

export type PermissionRef = {
    action: string;
    object: string;
};

export type ProviderInfo = {
    id: string;
    name: string;
};

export type SchemaDecimal = string;

export type UpdateAssetLocationRequest = {
    location: string;
};

export type UpdateAssetLocations = {
    home: string;
};

export type UpdateAssetRequest = {
    alias?: string | null;
    bundle?: string | null;
    locations: UpdateAssetLocations;
    notes?: string | null;
    tag: string;
};

export type UpdateLabelRequest = {
    blocking: boolean;
    colour?: string | null;
    description?: string | null;
    name: string;
};

export type UserDto = {
    email: string;
    id: string;
    is_admin: boolean;
    name: string;
};

export type ListAssetTypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/asset-types';
};

export type ListAssetTypesErrors = {
    /**
     * Missing permission
     */
    401: ErrorResponse;
};

export type ListAssetTypesError = ListAssetTypesErrors[keyof ListAssetTypesErrors];

export type ListAssetTypesResponses = {
    /**
     * Success
     */
    200: Array<AssetTypeDto>;
};

export type ListAssetTypesResponse = ListAssetTypesResponses[keyof ListAssetTypesResponses];

export type CreateAssetTypeData = {
    body: AssetType;
    path?: never;
    query?: never;
    url: '/asset-types';
};

export type CreateAssetTypeErrors = {
    /**
     * Manufacturer by that ID not found
     */
    400: ErrorResponse;
    /**
     * Missing permission
     */
    401: ErrorResponse;
};

export type CreateAssetTypeError = CreateAssetTypeErrors[keyof CreateAssetTypeErrors];

export type CreateAssetTypeResponses = {
    /**
     * Success
     */
    200: AssetTypeDto;
};

export type CreateAssetTypeResponse = CreateAssetTypeResponses[keyof CreateAssetTypeResponses];

export type DeleteAssetTypeByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/asset-types/{id}';
};

export type DeleteAssetTypeByIdErrors = {
    /**
     * Missing permission
     */
    401: ErrorResponse;
    /**
     * Asset type by that ID not found
     */
    404: ErrorResponse;
};

export type DeleteAssetTypeByIdError = DeleteAssetTypeByIdErrors[keyof DeleteAssetTypeByIdErrors];

export type DeleteAssetTypeByIdResponses = {
    /**
     * Success
     */
    204: void;
};

export type DeleteAssetTypeByIdResponse = DeleteAssetTypeByIdResponses[keyof DeleteAssetTypeByIdResponses];

export type GetAssetTypeByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/asset-types/{id}';
};

export type GetAssetTypeByIdErrors = {
    /**
     * Missing permission
     */
    401: ErrorResponse;
    /**
     * Asset type by that ID not found
     */
    404: ErrorResponse;
};

export type GetAssetTypeByIdError = GetAssetTypeByIdErrors[keyof GetAssetTypeByIdErrors];

export type GetAssetTypeByIdResponses = {
    /**
     * Success
     */
    200: AssetTypeDto;
};

export type GetAssetTypeByIdResponse = GetAssetTypeByIdResponses[keyof GetAssetTypeByIdResponses];

export type PatchAssetTypeByIdData = {
    body: PatchAssetType;
    path: {
        id: string;
    };
    query?: never;
    url: '/asset-types/{id}';
};

export type PatchAssetTypeByIdErrors = {
    /**
     * Missing permission
     */
    401: ErrorResponse;
    /**
     * Manufacturer by that ID not found
     */
    404: ErrorResponse;
};

export type PatchAssetTypeByIdError = PatchAssetTypeByIdErrors[keyof PatchAssetTypeByIdErrors];

export type PatchAssetTypeByIdResponses = {
    /**
     * Success
     */
    200: AssetTypeDto;
};

export type PatchAssetTypeByIdResponse = PatchAssetTypeByIdResponses[keyof PatchAssetTypeByIdResponses];

export type UpdateAssetTypeByIdData = {
    body: AssetType;
    path: {
        id: string;
    };
    query?: never;
    url: '/asset-types/{id}';
};

export type UpdateAssetTypeByIdErrors = {
    /**
     * Missing permission
     */
    401: ErrorResponse;
    /**
     * Asset type by that ID not found
     */
    404: ErrorResponse;
};

export type UpdateAssetTypeByIdError = UpdateAssetTypeByIdErrors[keyof UpdateAssetTypeByIdErrors];

export type UpdateAssetTypeByIdResponses = {
    /**
     * Success
     */
    200: AssetTypeDto;
};

export type UpdateAssetTypeByIdResponse = UpdateAssetTypeByIdResponses[keyof UpdateAssetTypeByIdResponses];

export type ListAssetsOfAssetTypeData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/asset-types/{id}/assets';
};

export type ListAssetsOfAssetTypeErrors = {
    /**
     * Missing permission
     */
    401: ErrorResponse;
    /**
     * Asset type by that ID not found
     */
    404: ErrorResponse;
};

export type ListAssetsOfAssetTypeError = ListAssetsOfAssetTypeErrors[keyof ListAssetsOfAssetTypeErrors];

export type ListAssetsOfAssetTypeResponses = {
    /**
     * Success
     */
    200: Array<AssetDto>;
};

export type ListAssetsOfAssetTypeResponse = ListAssetsOfAssetTypeResponses[keyof ListAssetsOfAssetTypeResponses];

export type ListAssetsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/assets';
};

export type ListAssetsErrors = {
    /**
     * Missing permission
     */
    401: ErrorResponse;
};

export type ListAssetsError = ListAssetsErrors[keyof ListAssetsErrors];

export type ListAssetsResponses = {
    /**
     * Success
     */
    200: Array<AssetDto>;
};

export type ListAssetsResponse = ListAssetsResponses[keyof ListAssetsResponses];

export type CreateAssetData = {
    body: CreateAssetRequest;
    path?: never;
    query?: never;
    url: '/assets';
};

export type CreateAssetErrors = {
    /**
     * Missing permission
     */
    401: ErrorResponse;
};

export type CreateAssetError = CreateAssetErrors[keyof CreateAssetErrors];

export type CreateAssetResponses = {
    /**
     * Success
     */
    200: AssetDto;
};

export type CreateAssetResponse = CreateAssetResponses[keyof CreateAssetResponses];

export type DeleteAssetByIdData = {
    body?: never;
    path: {
        /**
         * Requested asset ID
         */
        id: string;
    };
    query?: never;
    url: '/assets/{id}';
};

export type DeleteAssetByIdErrors = {
    /**
     * Missing permission
     */
    401: ErrorResponse;
    /**
     * Asset by that ID not found
     */
    404: ErrorResponse;
};

export type DeleteAssetByIdError = DeleteAssetByIdErrors[keyof DeleteAssetByIdErrors];

export type DeleteAssetByIdResponses = {
    /**
     * Success
     */
    204: void;
};

export type DeleteAssetByIdResponse = DeleteAssetByIdResponses[keyof DeleteAssetByIdResponses];

export type GetAssetByIdOrTagData = {
    body?: never;
    path: {
        /**
         * Requested asset ID
         */
        id: unknown;
    };
    query?: never;
    url: '/assets/{id}';
};

export type GetAssetByIdOrTagErrors = {
    /**
     * Missing permission
     */
    401: ErrorResponse;
    /**
     * Asset by that ID or Tag not found
     */
    404: ErrorResponse;
};

export type GetAssetByIdOrTagError = GetAssetByIdOrTagErrors[keyof GetAssetByIdOrTagErrors];

export type GetAssetByIdOrTagResponses = {
    /**
     * Success
     */
    200: AssetDto;
};

export type GetAssetByIdOrTagResponse = GetAssetByIdOrTagResponses[keyof GetAssetByIdOrTagResponses];

export type UpdateAssetByIdData = {
    body: UpdateAssetRequest;
    path: {
        /**
         * Requested asset ID
         */
        id: string;
    };
    query?: never;
    url: '/assets/{id}';
};

export type UpdateAssetByIdErrors = {
    /**
     * Missing permission
     */
    401: ErrorResponse;
    /**
     * Asset by that ID not found
     */
    404: ErrorResponse;
};

export type UpdateAssetByIdError = UpdateAssetByIdErrors[keyof UpdateAssetByIdErrors];

export type UpdateAssetByIdResponses = {
    /**
     * Success
     */
    204: void;
};

export type UpdateAssetByIdResponse = UpdateAssetByIdResponses[keyof UpdateAssetByIdResponses];

export type GetAssetLocationData = {
    body?: never;
    path: {
        /**
         * Requested asset ID
         */
        id: string;
    };
    query?: never;
    url: '/assets/{id}/location';
};

export type GetAssetLocationErrors = {
    /**
     * Missing permission
     */
    401: ErrorResponse;
    /**
     * Asset by that ID not found
     */
    404: ErrorResponse;
};

export type GetAssetLocationError = GetAssetLocationErrors[keyof GetAssetLocationErrors];

export type GetAssetLocationResponses = {
    /**
     * Success
     */
    200: LocationDto;
};

export type GetAssetLocationResponse = GetAssetLocationResponses[keyof GetAssetLocationResponses];

export type SetAssetLocationData = {
    body: UpdateAssetLocationRequest;
    path: {
        /**
         * Requested asset ID
         */
        id: string;
    };
    query?: never;
    url: '/assets/{id}/location';
};

export type SetAssetLocationErrors = {
    /**
     * Missing permission
     */
    401: ErrorResponse;
    /**
     * Asset by that ID not found
     */
    404: ErrorResponse;
};

export type SetAssetLocationError = SetAssetLocationErrors[keyof SetAssetLocationErrors];

export type SetAssetLocationResponses = {
    /**
     * Success
     */
    200: AssetDto;
};

export type SetAssetLocationResponse = SetAssetLocationResponses[keyof SetAssetLocationResponses];

export type ListAuthProvidersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/providers';
};

export type ListAuthProvidersResponses = {
    /**
     * Success
     */
    200: Array<ProviderInfo>;
};

export type ListAuthProvidersResponse = ListAuthProvidersResponses[keyof ListAuthProvidersResponses];

export type ListAssetBundlesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/bundles';
};

export type ListAssetBundlesErrors = {
    /**
     * Missing permission
     */
    401: ErrorResponse;
    /**
     * Asset bundle by that ID not found
     */
    404: ErrorResponse;
};

export type ListAssetBundlesError = ListAssetBundlesErrors[keyof ListAssetBundlesErrors];

export type ListAssetBundlesResponses = {
    /**
     * Success
     */
    200: Array<AssetBundleDto>;
};

export type ListAssetBundlesResponse = ListAssetBundlesResponses[keyof ListAssetBundlesResponses];

export type CreateAssetBundleData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/bundles';
};

export type CreateAssetBundleErrors = {
    /**
     * Missing permission
     */
    401: ErrorResponse;
};

export type CreateAssetBundleError = CreateAssetBundleErrors[keyof CreateAssetBundleErrors];

export type CreateAssetBundleResponses = {
    /**
     * Success
     */
    200: Array<AssetDto>;
};

export type CreateAssetBundleResponse = CreateAssetBundleResponses[keyof CreateAssetBundleResponses];

export type DeleteAssetBundleData = {
    body?: never;
    path: {
        /**
         * Requested asset bundle ID
         */
        id: string;
    };
    query?: never;
    url: '/bundles/{id}';
};

export type DeleteAssetBundleErrors = {
    /**
     * Missing permission
     */
    401: ErrorResponse;
    /**
     * Asset bundle by that ID not found
     */
    404: ErrorResponse;
};

export type DeleteAssetBundleError = DeleteAssetBundleErrors[keyof DeleteAssetBundleErrors];

export type DeleteAssetBundleResponses = {
    /**
     * Success
     */
    204: void;
};

export type DeleteAssetBundleResponse = DeleteAssetBundleResponses[keyof DeleteAssetBundleResponses];

export type GetAssetBundleByIdData = {
    body?: never;
    path: {
        /**
         * Requested asset bundle ID
         */
        id: string;
    };
    query?: never;
    url: '/bundles/{id}';
};

export type GetAssetBundleByIdErrors = {
    /**
     * Missing permission
     */
    401: ErrorResponse;
    /**
     * Asset bundle by that ID not found
     */
    404: ErrorResponse;
};

export type GetAssetBundleByIdError = GetAssetBundleByIdErrors[keyof GetAssetBundleByIdErrors];

export type GetAssetBundleByIdResponses = {
    /**
     * Success
     */
    200: AssetBundleDto;
};

export type GetAssetBundleByIdResponse = GetAssetBundleByIdResponses[keyof GetAssetBundleByIdResponses];

export type GetAssetsWithinBundleByIdData = {
    body?: never;
    path: {
        /**
         * Requested asset bundle ID
         */
        id: string;
    };
    query?: never;
    url: '/bundles/{id}/assets';
};

export type GetAssetsWithinBundleByIdErrors = {
    /**
     * Missing permission
     */
    401: ErrorResponse;
    /**
     * Asset bundle by that ID not found
     */
    404: ErrorResponse;
};

export type GetAssetsWithinBundleByIdError = GetAssetsWithinBundleByIdErrors[keyof GetAssetsWithinBundleByIdErrors];

export type GetAssetsWithinBundleByIdResponses = {
    /**
     * Success
     */
    200: Array<AssetDto>;
};

export type GetAssetsWithinBundleByIdResponse = GetAssetsWithinBundleByIdResponses[keyof GetAssetsWithinBundleByIdResponses];

export type GetContactDetailsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Referred asset ID or Tag.
         */
        asset: unknown;
    };
    url: '/contact';
};

export type GetContactDetailsErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponse;
};

export type GetContactDetailsError = GetContactDetailsErrors[keyof GetContactDetailsErrors];

export type GetContactDetailsResponses = {
    /**
     * Success
     */
    200: ContactDetailsDto;
};

export type GetContactDetailsResponse = GetContactDetailsResponses[keyof GetContactDetailsResponses];

export type ListGroupsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/groups';
};

export type ListGroupsResponses = {
    /**
     * Success
     */
    200: Array<GroupInfo>;
};

export type ListGroupsResponse = ListGroupsResponses[keyof ListGroupsResponses];

export type CreateGroupData = {
    body: CreateGroup;
    path?: never;
    query?: never;
    url: '/groups';
};

export type CreateGroupResponses = {
    /**
     * Success
     */
    200: GroupInfo;
};

export type CreateGroupResponse = CreateGroupResponses[keyof CreateGroupResponses];

export type GetGroupByIdData = {
    body?: never;
    path: {
        group_id: string;
    };
    query?: never;
    url: '/groups/{group_id}';
};

export type GetGroupByIdErrors = {
    /**
     * Not found
     */
    404: unknown;
};

export type GetGroupByIdResponses = {
    /**
     * Success
     */
    200: GroupInfo;
};

export type GetGroupByIdResponse = GetGroupByIdResponses[keyof GetGroupByIdResponses];

export type RemoveUserFromGroupData = {
    body: ModifyMember;
    path: {
        group_id: string;
    };
    query?: never;
    url: '/groups/{group_id}/members';
};

export type RemoveUserFromGroupErrors = {
    /**
     * Not found
     */
    404: unknown;
};

export type RemoveUserFromGroupResponses = {
    /**
     * Success
     */
    201: unknown;
};

export type ListGroupMembersData = {
    body?: never;
    path: {
        group_id: string;
    };
    query?: never;
    url: '/groups/{group_id}/members';
};

export type ListGroupMembersErrors = {
    /**
     * Not found
     */
    404: unknown;
};

export type ListGroupMembersResponses = {
    /**
     * Success
     */
    200: GroupMembers;
};

export type ListGroupMembersResponse = ListGroupMembersResponses[keyof ListGroupMembersResponses];

export type AddUserToGroupData = {
    body: ModifyMember;
    path: {
        group_id: string;
    };
    query?: never;
    url: '/groups/{group_id}/members';
};

export type AddUserToGroupErrors = {
    /**
     * Not found
     */
    404: unknown;
};

export type AddUserToGroupResponses = {
    /**
     * Success
     */
    201: unknown;
};

export type RemovePermissionFromGroupData = {
    body: PermissionRef;
    path: {
        group_id: string;
    };
    query?: never;
    url: '/groups/{group_id}/permissions';
};

export type RemovePermissionFromGroupErrors = {
    /**
     * Not found
     */
    404: unknown;
};

export type RemovePermissionFromGroupResponses = {
    /**
     * Success
     */
    201: unknown;
};

export type ListGroupPermissionsData = {
    body?: never;
    path: {
        group_id: string;
    };
    query?: never;
    url: '/groups/{group_id}/permissions';
};

export type ListGroupPermissionsErrors = {
    /**
     * Not found
     */
    404: unknown;
};

export type ListGroupPermissionsResponses = {
    /**
     * Success
     */
    200: Array<ObjectPermissions>;
};

export type ListGroupPermissionsResponse = ListGroupPermissionsResponses[keyof ListGroupPermissionsResponses];

export type AddPermissionToGroupData = {
    body: PermissionRef;
    path: {
        group_id: string;
    };
    query?: never;
    url: '/groups/{group_id}/permissions';
};

export type AddPermissionToGroupErrors = {
    /**
     * Not found
     */
    404: unknown;
};

export type AddPermissionToGroupResponses = {
    /**
     * Success
     */
    201: unknown;
};

export type HealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthResponses = {
    /**
     * Success
     */
    200: string;
};

export type HealthResponse = HealthResponses[keyof HealthResponses];

export type Health2Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type Health2Responses = {
    /**
     * Success
     */
    200: string;
};

export type Health2Response = Health2Responses[keyof Health2Responses];

export type ListLabelsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/labels';
};

export type ListLabelsErrors = {
    /**
     * Missing permission
     */
    401: ErrorResponse;
};

export type ListLabelsError = ListLabelsErrors[keyof ListLabelsErrors];

export type ListLabelsResponses = {
    /**
     * Success
     */
    200: Array<LabelDto>;
};

export type ListLabelsResponse = ListLabelsResponses[keyof ListLabelsResponses];

export type CreateLabelData = {
    body: CreateLabelRequest;
    path?: never;
    query?: never;
    url: '/labels';
};

export type CreateLabelErrors = {
    /**
     * Missing permission
     */
    401: ErrorResponse;
};

export type CreateLabelError = CreateLabelErrors[keyof CreateLabelErrors];

export type CreateLabelResponses = {
    /**
     * Success
     */
    200: LabelDto;
};

export type CreateLabelResponse = CreateLabelResponses[keyof CreateLabelResponses];

export type DeleteLabelByIdData = {
    body?: never;
    path: {
        /**
         * Requested label ID.
         */
        id: string;
    };
    query?: never;
    url: '/labels/{id}';
};

export type DeleteLabelByIdErrors = {
    /**
     * Missing permission
     */
    401: ErrorResponse;
    /**
     * Label by that ID not found
     */
    404: ErrorResponse;
};

export type DeleteLabelByIdError = DeleteLabelByIdErrors[keyof DeleteLabelByIdErrors];

export type DeleteLabelByIdResponses = {
    /**
     * Success
     */
    204: void;
};

export type DeleteLabelByIdResponse = DeleteLabelByIdResponses[keyof DeleteLabelByIdResponses];

export type GetLabelByIdData = {
    body?: never;
    path: {
        /**
         * Requested label ID.
         */
        id: string;
    };
    query?: never;
    url: '/labels/{id}';
};

export type GetLabelByIdErrors = {
    /**
     * Missing permission
     */
    401: ErrorResponse;
    /**
     * Label by that ID not found
     */
    404: ErrorResponse;
};

export type GetLabelByIdError = GetLabelByIdErrors[keyof GetLabelByIdErrors];

export type GetLabelByIdResponses = {
    /**
     * Success
     */
    200: LabelDto;
};

export type GetLabelByIdResponse = GetLabelByIdResponses[keyof GetLabelByIdResponses];

export type UpdateLabelByIdData = {
    body: UpdateLabelRequest;
    path: {
        /**
         * Requested label ID.
         */
        id: string;
    };
    query?: never;
    url: '/labels/{id}';
};

export type UpdateLabelByIdErrors = {
    /**
     * Missing permission
     */
    401: ErrorResponse;
    /**
     * Label by that ID not found
     */
    404: ErrorResponse;
};

export type UpdateLabelByIdError = UpdateLabelByIdErrors[keyof UpdateLabelByIdErrors];

export type UpdateLabelByIdResponses = {
    /**
     * Success
     */
    200: LabelDto;
};

export type UpdateLabelByIdResponse = UpdateLabelByIdResponses[keyof UpdateLabelByIdResponses];

export type ListLocationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/locations';
};

export type ListLocationsErrors = {
    /**
     * Missing permission
     */
    401: ErrorResponse;
};

export type ListLocationsError = ListLocationsErrors[keyof ListLocationsErrors];

export type ListLocationsResponses = {
    /**
     * Success
     */
    200: Array<LocationDto>;
};

export type ListLocationsResponse = ListLocationsResponses[keyof ListLocationsResponses];

export type CreateLocationData = {
    body: Location;
    path?: never;
    query?: never;
    url: '/locations';
};

export type CreateLocationErrors = {
    /**
     * Missing permission
     */
    401: ErrorResponse;
};

export type CreateLocationError = CreateLocationErrors[keyof CreateLocationErrors];

export type CreateLocationResponses = {
    /**
     * Success
     */
    200: LocationDto;
};

export type CreateLocationResponse = CreateLocationResponses[keyof CreateLocationResponses];

export type DeleteLocationByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/locations/{id}';
};

export type DeleteLocationByIdErrors = {
    /**
     * Missing permission
     */
    401: ErrorResponse;
    /**
     * Location by that ID not found
     */
    404: ErrorResponse;
};

export type DeleteLocationByIdError = DeleteLocationByIdErrors[keyof DeleteLocationByIdErrors];

export type DeleteLocationByIdResponses = {
    /**
     * Success
     */
    204: void;
};

export type DeleteLocationByIdResponse = DeleteLocationByIdResponses[keyof DeleteLocationByIdResponses];

export type GetLocationByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/locations/{id}';
};

export type GetLocationByIdErrors = {
    /**
     * Missing permission
     */
    401: ErrorResponse;
    /**
     * Location by that ID not found
     */
    404: ErrorResponse;
};

export type GetLocationByIdError = GetLocationByIdErrors[keyof GetLocationByIdErrors];

export type GetLocationByIdResponses = {
    /**
     * Success
     */
    200: LocationDto;
};

export type GetLocationByIdResponse = GetLocationByIdResponses[keyof GetLocationByIdResponses];

export type PatchLocationByIdData = {
    body: PatchLocation;
    path: {
        id: string;
    };
    query?: never;
    url: '/locations/{id}';
};

export type PatchLocationByIdErrors = {
    /**
     * Missing permission
     */
    401: ErrorResponse;
    /**
     * Location by that ID not found
     */
    404: ErrorResponse;
};

export type PatchLocationByIdError = PatchLocationByIdErrors[keyof PatchLocationByIdErrors];

export type PatchLocationByIdResponses = {
    /**
     * Success
     */
    200: LocationDto;
};

export type PatchLocationByIdResponse = PatchLocationByIdResponses[keyof PatchLocationByIdResponses];

export type UpdateLocationByIdData = {
    body: Location;
    path: {
        id: string;
    };
    query?: never;
    url: '/locations/{id}';
};

export type UpdateLocationByIdErrors = {
    /**
     * Missing permission
     */
    401: ErrorResponse;
    /**
     * Location by that ID not found
     */
    404: ErrorResponse;
};

export type UpdateLocationByIdError = UpdateLocationByIdErrors[keyof UpdateLocationByIdErrors];

export type UpdateLocationByIdResponses = {
    /**
     * Success
     */
    200: LocationDto;
};

export type UpdateLocationByIdResponse = UpdateLocationByIdResponses[keyof UpdateLocationByIdResponses];

export type ListManufacturersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/manufacturers';
};

export type ListManufacturersErrors = {
    /**
     * Missing permission
     */
    401: ErrorResponse;
};

export type ListManufacturersError = ListManufacturersErrors[keyof ListManufacturersErrors];

export type ListManufacturersResponses = {
    /**
     * Success
     */
    200: Array<ManufacturerInfo>;
};

export type ListManufacturersResponse = ListManufacturersResponses[keyof ListManufacturersResponses];

export type CreateManufacturerData = {
    body: Manufacturer;
    path?: never;
    query?: never;
    url: '/manufacturers';
};

export type CreateManufacturerErrors = {
    /**
     * Missing permission
     */
    401: ErrorResponse;
};

export type CreateManufacturerError = CreateManufacturerErrors[keyof CreateManufacturerErrors];

export type CreateManufacturerResponses = {
    /**
     * Success
     */
    200: ManufacturerInfo;
};

export type CreateManufacturerResponse = CreateManufacturerResponses[keyof CreateManufacturerResponses];

export type DeleteManufacturerByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/manufacturers/{id}';
};

export type DeleteManufacturerByIdErrors = {
    /**
     * Missing permission
     */
    401: ErrorResponse;
    /**
     * Manufacturer by that ID not found
     */
    404: ErrorResponse;
};

export type DeleteManufacturerByIdError = DeleteManufacturerByIdErrors[keyof DeleteManufacturerByIdErrors];

export type DeleteManufacturerByIdResponses = {
    /**
     * Success
     */
    204: void;
};

export type DeleteManufacturerByIdResponse = DeleteManufacturerByIdResponses[keyof DeleteManufacturerByIdResponses];

export type GetManufacturerByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/manufacturers/{id}';
};

export type GetManufacturerByIdErrors = {
    /**
     * Missing permission
     */
    401: ErrorResponse;
    /**
     * Manufacturer by that ID not found
     */
    404: ErrorResponse;
};

export type GetManufacturerByIdError = GetManufacturerByIdErrors[keyof GetManufacturerByIdErrors];

export type GetManufacturerByIdResponses = {
    /**
     * Success
     */
    200: ManufacturerInfo;
};

export type GetManufacturerByIdResponse = GetManufacturerByIdResponses[keyof GetManufacturerByIdResponses];

export type PatchManufacturerByIdData = {
    body: PatchManufacturer;
    path: {
        id: string;
    };
    query?: never;
    url: '/manufacturers/{id}';
};

export type PatchManufacturerByIdErrors = {
    /**
     * Missing permission
     */
    401: ErrorResponse;
    /**
     * Manufacturer by that ID not found
     */
    404: ErrorResponse;
};

export type PatchManufacturerByIdError = PatchManufacturerByIdErrors[keyof PatchManufacturerByIdErrors];

export type PatchManufacturerByIdResponses = {
    /**
     * Success
     */
    200: ManufacturerInfo;
};

export type PatchManufacturerByIdResponse = PatchManufacturerByIdResponses[keyof PatchManufacturerByIdResponses];

export type UpdateManufacturerByIdData = {
    body: Manufacturer;
    path: {
        id: string;
    };
    query?: never;
    url: '/manufacturers/{id}';
};

export type UpdateManufacturerByIdErrors = {
    /**
     * Missing permission
     */
    401: ErrorResponse;
    /**
     * Manufacturer by that ID not found
     */
    404: ErrorResponse;
};

export type UpdateManufacturerByIdError = UpdateManufacturerByIdErrors[keyof UpdateManufacturerByIdErrors];

export type UpdateManufacturerByIdResponses = {
    /**
     * Success
     */
    200: ManufacturerInfo;
};

export type UpdateManufacturerByIdResponse = UpdateManufacturerByIdResponses[keyof UpdateManufacturerByIdResponses];

export type ListManufacturerAssetTypesData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/manufacturers/{id}/asset-types';
};

export type ListManufacturerAssetTypesErrors = {
    /**
     * Missing permission
     */
    401: ErrorResponse;
    /**
     * Manufacturer by that ID not found
     */
    404: ErrorResponse;
};

export type ListManufacturerAssetTypesError = ListManufacturerAssetTypesErrors[keyof ListManufacturerAssetTypesErrors];

export type ListManufacturerAssetTypesResponses = {
    /**
     * Success
     */
    200: Array<AssetTypeDto>;
};

export type ListManufacturerAssetTypesResponse = ListManufacturerAssetTypesResponses[keyof ListManufacturerAssetTypesResponses];

export type ListUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users';
};

export type ListUsersResponses = {
    /**
     * Success
     */
    200: Array<UserDto>;
};

export type ListUsersResponse = ListUsersResponses[keyof ListUsersResponses];

export type GetCurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/@me';
};

export type GetCurrentUserResponses = {
    /**
     * Success
     */
    200: UserDto;
};

export type GetCurrentUserResponse = GetCurrentUserResponses[keyof GetCurrentUserResponses];

export type GetCurrentUserPermissionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/@me/permissions';
};

export type GetCurrentUserPermissionsResponses = {
    /**
     * Success
     */
    200: Array<ObjectPermissions>;
};

export type GetCurrentUserPermissionsResponse = GetCurrentUserPermissionsResponses[keyof GetCurrentUserPermissionsResponses];

export type GetUserByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/users/{id}';
};

export type GetUserByIdErrors = {
    /**
     * Missing permission
     */
    401: ErrorResponse;
    /**
     * User by that ID not found
     */
    404: ErrorResponse;
};

export type GetUserByIdError = GetUserByIdErrors[keyof GetUserByIdErrors];

export type GetUserByIdResponses = {
    /**
     * Success
     */
    200: UserDto;
};

export type GetUserByIdResponse = GetUserByIdResponses[keyof GetUserByIdResponses];
