// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zAssetBundleDto = z.object({
    id: z.uuid()
});

export const zAssetLocations = z.object({
    current: z.uuid(),
    home: z.uuid()
});

export const zAssetDto = z.object({
    alias: z.string().nullish(),
    bundle: z.uuid().nullish(),
    id: z.uuid(),
    locations: zAssetLocations,
    notes: z.string().nullish(),
    tag: z.string(),
    type: z.uuid()
});

export const zContactDetailsLinkDto = z.object({
    label: z.string().nullish(),
    link: z.url()
});

export const zContactDetailsDto = z.object({
    links: z.array(zContactDetailsLinkDto),
    name: z.string().nullish()
});

export const zCoordinates = z.tuple([z.number(), z.number()]);

export const zCreateAssetRequest = z.object({
    alias: z.string().nullish(),
    bundle: z.uuid().nullish(),
    locations: zAssetLocations,
    notes: z.string().nullish(),
    tag: z.string(),
    type: z.uuid()
});

export const zCreateGroup = z.object({
    name: z.string()
});

export const zErrorResponse = z.object({
    error: z.string()
});

export const zGroupInfo = z.object({
    id: z.uuid(),
    name: z.string()
});

export const zLocation = z.object({
    coordinates: zCoordinates.nullish(),
    description: z.string().nullish(),
    name: z.string()
});

export const zLocationDto = z.object({
    coordinates: zCoordinates.nullish(),
    description: z.string().nullish(),
    id: z.uuid(),
    name: z.string()
});

export const zManufacturer = z.object({
    description: z.string().nullish(),
    email: z.string().nullish(),
    name: z.string(),
    phone: z.string().nullish(),
    website: z.string().nullish()
});

export const zManufacturerInfo = z.object({
    description: z.string().nullish(),
    email: z.string().nullish(),
    id: z.uuid(),
    name: z.string(),
    phone: z.string().nullish(),
    website: z.string().nullish()
});

export const zModifyMember = z.object({
    member: z.uuid()
});

export const zObjectPermissions = z.object({
    actions: z.array(z.string()),
    name: z.string()
});

export const zPatchLocation = z.object({
    coordinates: zCoordinates.nullish(),
    description: z.string().nullish(),
    name: z.string().nullish()
});

export const zPatchManufacturer = z.object({
    description: z.string().nullish(),
    email: z.string().nullish(),
    name: z.string().nullish(),
    phone: z.string().nullish(),
    website: z.string().nullish()
});

export const zPermissionRef = z.object({
    action: z.string(),
    object: z.string()
});

export const zProviderInfo = z.object({
    id: z.string(),
    name: z.string()
});

export const zSchemaDecimal = z.string();

export const zAssetType = z.object({
    manufacturer: z.uuid(),
    name: z.string(),
    product_url: z.url().nullish(),
    value: zSchemaDecimal.nullish()
});

export const zAssetTypeDto = z.object({
    id: z.uuid(),
    manufacturer: z.uuid(),
    name: z.string(),
    product_url: z.url().nullish(),
    value: zSchemaDecimal.nullish()
});

export const zPatchAssetType = z.object({
    manufacturer: z.uuid().nullish(),
    name: z.string().nullish(),
    product_url: z.string().nullish(),
    value: zSchemaDecimal.nullish()
});

export const zUpdateAssetLocationRequest = z.object({
    location: z.uuid()
});

export const zUpdateAssetLocations = z.object({
    home: z.uuid()
});

export const zUpdateAssetRequest = z.object({
    alias: z.string().nullish(),
    bundle: z.uuid().nullish(),
    locations: zUpdateAssetLocations,
    notes: z.string().nullish(),
    tag: z.string()
});

export const zUserDto = z.object({
    email: z.string(),
    id: z.uuid(),
    is_admin: z.boolean(),
    name: z.string()
});

export const zGroupMembers = z.object({
    members: z.array(zUserDto)
});

/**
 * Success
 */
export const zListAssetTypesResponse = z.array(zAssetTypeDto);

export const zCreateAssetTypeBody = zAssetType;

/**
 * Success
 */
export const zCreateAssetTypeResponse = zAssetTypeDto;

export const zDeleteAssetTypeByIdPath = z.object({
    id: z.uuid()
});

/**
 * Success
 */
export const zDeleteAssetTypeByIdResponse = z.void();

export const zGetAssetTypeByIdPath = z.object({
    id: z.uuid()
});

/**
 * Success
 */
export const zGetAssetTypeByIdResponse = zAssetTypeDto;

export const zPatchAssetTypeByIdBody = zPatchAssetType;

export const zPatchAssetTypeByIdPath = z.object({
    id: z.uuid()
});

/**
 * Success
 */
export const zPatchAssetTypeByIdResponse = zAssetTypeDto;

export const zUpdateAssetTypeByIdBody = zAssetType;

export const zUpdateAssetTypeByIdPath = z.object({
    id: z.uuid()
});

/**
 * Success
 */
export const zUpdateAssetTypeByIdResponse = zAssetTypeDto;

export const zListAssetsOfAssetTypePath = z.object({
    id: z.uuid()
});

/**
 * Success
 */
export const zListAssetsOfAssetTypeResponse = z.array(zAssetDto);

/**
 * Success
 */
export const zListAssetsResponse = z.array(zAssetDto);

export const zCreateAssetBody = zCreateAssetRequest;

/**
 * Success
 */
export const zCreateAssetResponse = zAssetDto;

export const zDeleteAssetByIdPath = z.object({
    id: z.uuid()
});

/**
 * Success
 */
export const zDeleteAssetByIdResponse = z.void();

export const zGetAssetByIdOrTagPath = z.object({
    id: z.unknown()
});

/**
 * Success
 */
export const zGetAssetByIdOrTagResponse = zAssetDto;

export const zUpdateAssetByIdBody = zUpdateAssetRequest;

export const zUpdateAssetByIdPath = z.object({
    id: z.uuid()
});

/**
 * Success
 */
export const zUpdateAssetByIdResponse = z.void();

export const zGetAssetLocationPath = z.object({
    id: z.uuid()
});

/**
 * Success
 */
export const zGetAssetLocationResponse = zLocationDto;

export const zSetAssetLocationBody = zUpdateAssetLocationRequest;

export const zSetAssetLocationPath = z.object({
    id: z.uuid()
});

/**
 * Success
 */
export const zSetAssetLocationResponse = zAssetDto;

/**
 * Success
 */
export const zListAuthProvidersResponse = z.array(zProviderInfo);

/**
 * Success
 */
export const zListAssetBundlesResponse = z.array(zAssetBundleDto);

/**
 * Success
 */
export const zCreateAssetBundleResponse = z.array(zAssetDto);

export const zDeleteAssetBundlePath = z.object({
    id: z.uuid()
});

/**
 * Success
 */
export const zDeleteAssetBundleResponse = z.void();

export const zGetAssetBundleByIdPath = z.object({
    id: z.uuid()
});

/**
 * Success
 */
export const zGetAssetBundleByIdResponse = zAssetBundleDto;

export const zGetAssetsWithinBundleByIdPath = z.object({
    id: z.uuid()
});

/**
 * Success
 */
export const zGetAssetsWithinBundleByIdResponse = z.array(zAssetDto);

export const zGetContactDetailsQuery = z.object({
    asset: z.unknown()
});

/**
 * Success
 */
export const zGetContactDetailsResponse = zContactDetailsDto;

/**
 * Success
 */
export const zListGroupsResponse = z.array(zGroupInfo);

export const zCreateGroupBody = zCreateGroup;

/**
 * Success
 */
export const zCreateGroupResponse = zGroupInfo;

export const zGetGroupByIdPath = z.object({
    group_id: z.uuid()
});

/**
 * Success
 */
export const zGetGroupByIdResponse = zGroupInfo;

export const zRemoveUserFromGroupBody = zModifyMember;

export const zRemoveUserFromGroupPath = z.object({
    group_id: z.uuid()
});

export const zListGroupMembersPath = z.object({
    group_id: z.uuid()
});

/**
 * Success
 */
export const zListGroupMembersResponse = zGroupMembers;

export const zAddUserToGroupBody = zModifyMember;

export const zAddUserToGroupPath = z.object({
    group_id: z.uuid()
});

export const zRemovePermissionFromGroupBody = zPermissionRef;

export const zRemovePermissionFromGroupPath = z.object({
    group_id: z.uuid()
});

export const zListGroupPermissionsPath = z.object({
    group_id: z.uuid()
});

/**
 * Success
 */
export const zListGroupPermissionsResponse = z.array(zObjectPermissions);

export const zAddPermissionToGroupBody = zPermissionRef;

export const zAddPermissionToGroupPath = z.object({
    group_id: z.uuid()
});

/**
 * Success
 */
export const zHealthResponse = z.string();

/**
 * Success
 */
export const zHealth2Response = z.string();

/**
 * Success
 */
export const zListLocationsResponse = z.array(zLocationDto);

export const zCreateLocationBody = zLocation;

/**
 * Success
 */
export const zCreateLocationResponse = zLocationDto;

export const zDeleteLocationByIdPath = z.object({
    id: z.uuid()
});

/**
 * Success
 */
export const zDeleteLocationByIdResponse = z.void();

export const zGetLocationByIdPath = z.object({
    id: z.uuid()
});

/**
 * Success
 */
export const zGetLocationByIdResponse = zLocationDto;

export const zPatchLocationByIdBody = zPatchLocation;

export const zPatchLocationByIdPath = z.object({
    id: z.uuid()
});

/**
 * Success
 */
export const zPatchLocationByIdResponse = zLocationDto;

export const zUpdateLocationByIdBody = zLocation;

export const zUpdateLocationByIdPath = z.object({
    id: z.uuid()
});

/**
 * Success
 */
export const zUpdateLocationByIdResponse = zLocationDto;

/**
 * Success
 */
export const zListManufacturersResponse = z.array(zManufacturerInfo);

export const zCreateManufacturerBody = zManufacturer;

/**
 * Success
 */
export const zCreateManufacturerResponse = zManufacturerInfo;

export const zDeleteManufacturerByIdPath = z.object({
    id: z.uuid()
});

/**
 * Success
 */
export const zDeleteManufacturerByIdResponse = z.void();

export const zGetManufacturerByIdPath = z.object({
    id: z.uuid()
});

/**
 * Success
 */
export const zGetManufacturerByIdResponse = zManufacturerInfo;

export const zPatchManufacturerByIdBody = zPatchManufacturer;

export const zPatchManufacturerByIdPath = z.object({
    id: z.uuid()
});

/**
 * Success
 */
export const zPatchManufacturerByIdResponse = zManufacturerInfo;

export const zUpdateManufacturerByIdBody = zManufacturer;

export const zUpdateManufacturerByIdPath = z.object({
    id: z.uuid()
});

/**
 * Success
 */
export const zUpdateManufacturerByIdResponse = zManufacturerInfo;

export const zListManufacturerAssetTypesPath = z.object({
    id: z.uuid()
});

/**
 * Success
 */
export const zListManufacturerAssetTypesResponse = z.array(zAssetTypeDto);

/**
 * Success
 */
export const zListUsersResponse = z.array(zUserDto);

/**
 * Success
 */
export const zGetCurrentUserResponse = zUserDto;

/**
 * Success
 */
export const zGetCurrentUserPermissionsResponse = z.array(zObjectPermissions);

export const zGetUserByIdPath = z.object({
    id: z.uuid()
});

/**
 * Success
 */
export const zGetUserByIdResponse = zUserDto;
