// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zCreateGroup = z.object({
    name: z.string()
});

export const zErrorResponse = z.object({
    error: z.string()
});

export const zGroupInfo = z.object({
    id: z.uuid(),
    name: z.string()
});

export const zManufacturer = z.object({
    description: z.string().nullish(),
    email: z.string().nullish(),
    name: z.string(),
    phone: z.string().nullish(),
    website: z.string().nullish()
});

export const zManufacturerInfo = z.object({
    description: z.string().nullish(),
    email: z.string().nullish(),
    id: z.uuid(),
    name: z.string(),
    phone: z.string().nullish(),
    website: z.string().nullish()
});

export const zModifyMember = z.object({
    member: z.uuid()
});

export const zObjectPermissions = z.object({
    actions: z.array(z.string()),
    name: z.string()
});

export const zPatchManufacturer = z.object({
    description: z.string().nullish(),
    email: z.string().nullish(),
    name: z.string().nullish(),
    phone: z.string().nullish(),
    website: z.string().nullish()
});

export const zPermissionRef = z.object({
    action: z.string(),
    object: z.string()
});

export const zProviderInfo = z.object({
    id: z.string(),
    name: z.string()
});

export const zSchemaDecimal = z.number();

export const zAssetType = z.object({
    manufacturer: z.uuid(),
    name: z.string(),
    product_url: z.url().nullish(),
    value: zSchemaDecimal.nullish()
});

export const zAssetTypeDto = z.object({
    id: z.uuid(),
    manufacturer: z.uuid(),
    name: z.string(),
    product_url: z.url().nullish(),
    value: zSchemaDecimal.nullish()
});

export const zPatchAssetType = z.object({
    manufacturer: z.uuid().nullish(),
    name: z.string().nullish(),
    product_url: z.string().nullish(),
    value: zSchemaDecimal.nullish()
});

export const zUserInfo = z.object({
    email: z.string(),
    id: z.uuid(),
    name: z.string()
});

export const zGroupMembers = z.object({
    members: z.array(zUserInfo)
});

/**
 * Success
 */
export const zListAssetTypesResponse = z.array(zAssetTypeDto);

export const zCreateAssetTypeBody = zAssetType;

/**
 * Success
 */
export const zCreateAssetTypeResponse = zAssetTypeDto;

export const zDeleteAssetTypeByIdPath = z.object({
    id: z.uuid()
});

/**
 * Success
 */
export const zDeleteAssetTypeByIdResponse = z.void();

export const zGetAssetTypeByIdPath = z.object({
    id: z.uuid()
});

/**
 * Success
 */
export const zGetAssetTypeByIdResponse = zAssetTypeDto;

export const zPatchAssetTypeByIdBody = zPatchAssetType;

export const zPatchAssetTypeByIdPath = z.object({
    id: z.uuid()
});

/**
 * Success
 */
export const zPatchAssetTypeByIdResponse = zAssetTypeDto;

export const zUpdateAssetTypeByIdBody = zAssetType;

export const zUpdateAssetTypeByIdPath = z.object({
    id: z.uuid()
});

/**
 * Success
 */
export const zUpdateAssetTypeByIdResponse = zAssetTypeDto;

/**
 * Success
 */
export const zListAuthProvidersResponse = z.array(zProviderInfo);

/**
 * Success
 */
export const zListGroupsResponse = z.array(zGroupInfo);

export const zCreateGroupBody = zCreateGroup;

/**
 * Success
 */
export const zCreateGroupResponse = zGroupInfo;

export const zGetGroupByIdPath = z.object({
    group_id: z.uuid()
});

/**
 * Success
 */
export const zGetGroupByIdResponse = zGroupInfo;

export const zRemoveUserFromGroupBody = zModifyMember;

export const zRemoveUserFromGroupPath = z.object({
    group_id: z.uuid()
});

export const zListGroupMembersPath = z.object({
    group_id: z.uuid()
});

/**
 * Success
 */
export const zListGroupMembersResponse = zGroupMembers;

export const zAddUserToGroupBody = zModifyMember;

export const zAddUserToGroupPath = z.object({
    group_id: z.uuid()
});

export const zRemovePermissionFromGroupBody = zPermissionRef;

export const zRemovePermissionFromGroupPath = z.object({
    group_id: z.uuid()
});

export const zListGroupPermissionsPath = z.object({
    group_id: z.uuid()
});

/**
 * Success
 */
export const zListGroupPermissionsResponse = z.array(zObjectPermissions);

export const zAddPermissionToGroupBody = zPermissionRef;

export const zAddPermissionToGroupPath = z.object({
    group_id: z.uuid()
});

/**
 * Success
 */
export const zHealthResponse = z.string();

/**
 * Success
 */
export const zHealth2Response = z.string();

/**
 * Success
 */
export const zListManufacturersResponse = z.array(zManufacturerInfo);

export const zCreateManufacturerBody = zManufacturer;

/**
 * Success
 */
export const zCreateManufacturerResponse = zManufacturerInfo;

export const zDeleteManufacturerByIdPath = z.object({
    id: z.uuid()
});

/**
 * Success
 */
export const zDeleteManufacturerByIdResponse = z.void();

export const zGetManufacturerByIdPath = z.object({
    id: z.uuid()
});

/**
 * Success
 */
export const zGetManufacturerByIdResponse = zManufacturerInfo;

export const zPatchManufacturerByIdBody = zPatchManufacturer;

export const zPatchManufacturerByIdPath = z.object({
    id: z.uuid()
});

/**
 * Success
 */
export const zPatchManufacturerByIdResponse = zManufacturerInfo;

export const zUpdateManufacturerByIdBody = zManufacturer;

export const zUpdateManufacturerByIdPath = z.object({
    id: z.uuid()
});

/**
 * Success
 */
export const zUpdateManufacturerByIdResponse = zManufacturerInfo;

/**
 * Success
 */
export const zListUsersResponse = z.array(zUserInfo);

/**
 * Success
 */
export const zGetCurrentUserResponse = zUserInfo;

/**
 * Success
 */
export const zGetCurrentUserPermissionsResponse = z.array(zObjectPermissions);
