nodeLinker: node-modules

npmMinimalAgeGate: 0

yarnPath: .yarn/releases/yarn-4.16.0.cjs

supportedArchitectures:
  cpu:
    - 'current'
    - 'x64'
  os:
    - 'current'
    - 'linux'
  libc:
    - 'current'
    - 'musl'
